spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-offset-reset: latest
  cloud:
    stream:
      bindings:
        my-scs-input:     #自定义message channel名称
          binder: myRabbit
          destination: scs-exchange
          group: scs-queue
          content-type: application/json
        my-scs-output:     #自定义message channel名称
          binder: myRabbit
          destination: scs-exchange
          group: scs-queue
          content-type: application/json
        my-scs-kafka-output:
          binder: myKafka
          destination: my-kafka
          group: my-kafka
          content-type: application/json
        my-scs-kafka-input:
          binder: myKafka
          destination: my-kafka
          group: my-kafka
          content-type: application/json
      binders:
        myRabbit: #自定义默认binder名称
          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                addresses: 192.168.0.33
#                port: 5672
#                username: user
#                password: 123456
#                virtual-host: /test
        myKafka:
          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: http://192.168.0.33:9092
#                      auto-add-partitions: true
#                      auto-create-topics: true
#                      min-partition-count: 1
#                      configuration:
#                        sasl.mechanism: SCRAM-SHA-256
#                        security.protocol: SASL_PLAINTEXT
#                        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required
#                          username="${KAFKA.USER:admin}"
#                          password="${KAFKA.USER.PASSWORD}";
      defaultBinder: myRabbit

