spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-offset-reset: latest
  cloud:
    stream:
      bindings:
        my-scs-input:     #自定义message channel名称
          binder: myRabbit
          destination: scs-exchange
          group: scs-queue
          content-type: application/json
        my-scs-output:     #自定义message channel名称
          binder: myRabbit
          destination: scs-exchange
          group: scs-queue
          content-type: application/json
        my-scs-kafka-output:
          binder: myKafka
          destination: my-scs-kafka-output
          group: test-consumer-group
          content-type: application/json
        my-scs-kafka-input:
          binder: myKafka
          destination: my-scs-kafka-output
          group: test-consumer-group
          content-type: application/json
      binders:
        myRabbit: #自定义默认binder名称
          type: rabbit
        myKafka:
          type: kafka
      defaultBinder: myRabbit

